### ISSUE TITLE
Comments summarize after the presentation at Ekito 

### ISSUE THREAD

**Issue by NotBad4U** [loganmzz/rust-presentation-introduction#4]
## other languages
- [x] Remove affordance

## what we want
- [x] Remove efficiency 

## Fast
- [x] explain llvm (what's a backend compiler)

## First Code, Types
- [x] Merge the two
- [x] Put piece of code directly in the presentation. Don't pass by the IDE
- [x] Speak about immutability by default
- [x] Type inference

## Safety
- [x] **JVM**: Replace `JVM` with more generic name `Managed runtime/environment` or `Virtual Machine`
- [x] **Java/C++ Runtime Errors**: Merge slides
- [x] **Debugger**: Fix typo "debuger" => "debug**G**er"
- [x] remove gc image, keep the text

## Rust solution
- [x] remove lifetime

## Ownership
- [x] Merge slides on `move`

## TO CONCLUDE
- [x] Remove GC keep just safety
- [x] change title

## Parallelism
- [x] Remove drop
- [x] **Box**: Remove unknown size (idem for recursive types ?)
- [x] **Box**: Adds more concrete example
- [x] Remove Arc
- [x] **Thread**: Merge into **Send/Sync**
- [x] Better explain on SEND and SYNC 
- [x] Highlight what's SEND in the program
- [x] Explain data race

## Macros
- [x] Repeat `abstract over` for each line
- [x] Keep it simple ! Just one slide
- [x] just you can access to the AST

## CARGO WORKFLOW
- [x] just a workflow/build tool and not a dependency manager
- [x] Remove cargo extensions 

## Ecosystem
- [x] Adds RLS

## Libs
- [x] Example of rayon
- [x] Short code for rayon

## Conclusion
- [x] Remove GC
- [x] Put without

**Comment by NotBad4U** [comment]
I think we can close this issue too

**Comment by loganmzz** [comment]
Still some few things to be fixed.

**Comment by NotBad4U** [comment]
So I'll modify the "TO CONCLUDE" title for "CONCLUSION ABOUT OWNERSHIP/BORROWING"

**Comment by loganmzz** [comment]
Also need to fix "debugGer" gif ;)

**Comment by loganmzz** [comment]
"debugGer" typo send to issue #8
