### ISSUE TITLE
Improves theme colors

### ISSUE THREAD

**Issue by loganmzz** [loganmzz/rust-presentation-introduction#5]
- [ ] Strong (currently in red) don't show up clearly 
- [x] More basic colors for macro components

**Comment by NotBad4U** [comment]
Maybe we should take a light red (or hight tint) or switch to a high purple instead of this red. 
I think we'll get a better contrast with the dark background and that will increase the visibility.

PS: Same for the green and blue color in the macro slide.

**Comment by loganmzz** [comment]
Macros slide colors comes from highlight.js theme, but code background isn't same as slides. Which I think why they aren't rendering well.

I need to make some tests with bad displays
